### ISSUE TITLE
Not working and Error in log file  "ERROR - Error while processing hook smartfilamentsensor for phase sent:"

### ISSUE THREAD

**Issue by pixiandreas** [Royrdan/Octoprint-Smart-Filament-Sensor#26]
I got this ERROR in the log all the time.

I have test the sensor in the test menu in the GUI and it works there but not in real print :-)
Any idea how to solve it ?
 

`TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2022-10-11 22:05:52,396 - octoprint.plugins.smartfilamentsensor - DEBUG - ----- RUNNING calc_distance -----
2022-10-11 22:05:52,397 - octoprint.plugins.smartfilamentsensor - DEBUG - Found extrude command in 'G1 X114.713 Y110.03 E251.47017' with value: 251.47017
2022-10-11 22:05:52,400 - octoprint.util.comm - ERROR - Error while processing hook smartfilamentsensor for phase sent:
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/comm.py", line 4670, in _process_command_phase
    tags=tags,
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1688, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_smart_filament_sensor/__init__.py", line 401, in distance_detection
    self.calc_distance(float(extruder))
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_smart_filament_sensor/__init__.py", line 272, in calc_distance
    if (datetime.now() - self.last_movement_time).total_seconds() > 10:
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2022-10-11 22:05:52,476 - octoprint.plugins.smartfilamentsensor - DEBUG - ----- RUNNING calc_distance -----
2022-10-11 22:05:52,477 - octoprint.plugins.smartfilamentsensor - DEBUG - Found extrude command in 'G1 X114.831 Y109.973 E251.47453' with value: 251.47453
2022-10-11 22:05:52,480 - octoprint.util.comm - ERROR - Error while processing hook smartfilamentsensor for phase sent:
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/comm.py", line 4670, in _process_command_phase
    tags=tags,
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1688, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_smart_filament_sensor/__init__.py", line 401, in distance_detection
    self.calc_distance(float(extruder))
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_smart_filament_sensor/__init__.py", line 272, in calc_distance
    if (datetime.now() - self.last_movement_time).total_seconds() > 10:
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2022-10-11 22:05:52,504 - octoprint.plugins.smartfilamentsensor - DEBUG - ----- RUNNING calc_distance -----
2022-10-11 22:05:52,505 - octoprint.plugins.smartfilamentsensor - DEBUG - Found extrude command in 'G1 X114.897 Y109.892 E251.47801' with value: 251.47801
2022-10-11 22:05:52,507 - octoprint.util.comm - ERROR - Error while processing hook smartfilamentsensor for phase sent:
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/comm.py", line 4670, in _process_command_phase
    tags=tags,
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1688, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_smart_filament_sensor/__init__.py", line 401, in distance_detection`

**Comment by pixiandreas** [comment]
A reboot of the Raspberry pi solve this issue.

**Comment by pixiandreas** [comment]
.

**Comment by pixiandreas** [comment]
A reboot solve this issue.
